const DB='sak-db',TX='transactions',SET='settings';let db,route='home',filter='all',query='';
const cats={income:['Gaji','Freelance','Hadiah','Investasi','Lainnya'],expense:['Makanan','Transportasi','Rumah','Belanja','Tagihan','Kesehatan','Pendidikan','Hiburan','Pribadi','Lainnya']};
function openDB(){return new Promise((ok,bad)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{let d=r.result;d.createObjectStore(TX,{keyPath:'id',autoIncrement:true});d.createObjectStore(SET,{keyPath:'key'})};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>bad(r.error)})}
function store(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
function all(){return new Promise((ok,bad)=>{let r=store(TX).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function put(x){return new Promise((ok,bad)=>{let r=store(TX,'readwrite').put(x);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function del(id){return new Promise((ok,bad)=>{let r=store(TX,'readwrite').delete(id);r.onsuccess=ok;r.onerror=()=>bad(r.error)})}
function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)}
function dt(x){return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(x))}
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(s){let t=document.querySelector('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function go(r){route=r;location.hash=r;render()}
function row(x){return `<div class="tx" onclick="detail(${x.id})"><div class="tx-icon">${x.type==='income'?'＋':'−'}</div><div class="tx-main"><strong>${esc(x.category)}</strong><small>${dt(x.date)}${x.note?' · '+esc(x.note):''}</small></div><b class="${x.type}">${x.type==='income'?'+':'−'}${money(x.amount)}</b></div>`}
async function render(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));let tx=await all();if(route==='home')home(tx);else if(route==='transactions')transactions(tx);else if(route==='add')add();else if(route==='reports')reports(tx);else if(route==='settings')settings();else if(route==='detail')detailPage(tx.find(x=>x.id==location.hash.split('/')[1]))}
function home(tx){let i=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),o=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0);document.querySelector('#screen').innerHTML=`<section class="page"><div class="hero"><small>Saldo</small><div class="balance">${money(i-o)}</div></div><div class="grid"><div class="card"><span class="muted">Pemasukan</span><div class="money income">${money(i)}</div></div><div class="card"><span class="muted">Pengeluaran</span><div class="money expense">${money(o)}</div></div></div><div class="actions"><button class="action income" onclick="newTx('income')">＋ Pemasukan</button><button class="action expense" onclick="newTx('expense')">− Pengeluaran</button></div><div class="section"><h3>Transaksi terbaru</h3><button class="link" onclick="go('transactions')">Lihat semua</button></div><div class="card">${tx.sort((a,b)=>b.date-a.date||b.id-a.id).slice(0,8).map(row).join('')||'<div class="empty">Belum ada transaksi.<br>Yuk mulai mencatat.</div>'}</div></section>`}
function transactions(tx){let l=tx.filter(x=>filter==='all'||x.type===filter).filter(x=>(x.category+' '+x.note).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date-a.date||b.id-a.id);document.querySelector('#screen').innerHTML=`<section class="page"><h2>Transaksi</h2><div style="margin-top:14px"><input class="search" placeholder="Cari transaksi..." value="${esc(query)}" oninput="query=this.value;render()"></div><div class="toolbar"><button class="tab ${filter==='all'?'active':''}" onclick="filter='all';render()">Semua</button><button class="tab ${filter==='income'?'active':''}" onclick="filter='income';render()">Pemasukan</button><button class="tab ${filter==='expense'?'active':''}" onclick="filter='expense';render()">Pengeluaran</button></div><div class="card">${l.map(row).join('')||'<div class="empty">Tidak ada transaksi.</div>'}</div><button class="primary" style="margin-top:15px" onclick="newTx()">＋ Tambah transaksi</button></section>`}
let editing=null,forcedType='expense';
function newTx(t='expense'){editing=null;forcedType=t;go('add')}
function add(){let x=editing;let type=x?.type||forcedType;document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>${x?'Edit':'Tambah'} Transaksi</h2><button class="link" onclick="go('home')">Batal</button></div><form class="form" onsubmit="save(event)"><div class="field"><label>Tipe</label><select id="type"><option value="income" ${type==='income'?'selected':''}>Pemasukan</option><option value="expense" ${type==='expense'?'selected':''}>Pengeluaran</option></select></div><div class="field"><label>Nominal</label><input id="amount" class="amount" type="number" min="1" step="1" required value="${x?.amount||''}" placeholder="0"></div><div class="field"><label>Kategori</label><select id="category">${cats[type].map(c=>`<option ${c===x?.category?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Tanggal</label><input id="date" type="date" required value="${x?new Date(x.date).toISOString().slice(0,10):new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Catatan (opsional)</label><textarea id="note" rows="3">${esc(x?.note||'')}</textarea></div><button class="primary">Simpan</button></form></section>`}
async function save(e){e.preventDefault();let x={id:editing?.id,type:document.querySelector('#type').value,amount:Number(document.querySelector('#amount').value),category:document.querySelector('#category').value,date:new Date(document.querySelector('#date').value+'T12:00:00').getTime(),note:document.querySelector('#note').value,createdAt:editing?.createdAt||Date.now(),updatedAt:Date.now()};if(!(x.amount>0)||!x.category)return;await put(x);toast(editing?'Transaksi diperbarui':'Transaksi tersimpan');go('home')}
async function detail(id){location.hash='detail/'+id;route='detail';render()}
async function detailPage(x){if(!x){go('transactions');return}document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Detail Transaksi</h2><button class="link" onclick="go('transactions')">Kembali</button></div><div class="card"><span class="muted">${x.type==='income'?'Pemasukan':'Pengeluaran'}</span><h1 class="${x.type}">${x.type==='income'?'+':'−'}${money(x.amount)}</h1><p><b>Kategori</b><br>${esc(x.category)}</p><br><p><b>Tanggal</b><br>${dt(x.date)}</p><br><p><b>Catatan</b><br>${esc(x.note||'—')}</p></div><div class="actions"><button class="action" onclick="edit(${x.id})">✎ Edit</button><button class="action danger" onclick="removeTx(${x.id})">Hapus</button></div></section>`}
async function edit(id){editing=(await all()).find(x=>x.id===id);go('add')}
async function removeTx(id){if(confirm('Hapus transaksi ini secara permanen?')){await del(id);toast('Transaksi dihapus');go('transactions')}}
function reports(tx){let i=tx.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),o=tx.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),m={};tx.filter(x=>x.type==='expense').forEach(x=>m[x.category]=(m[x.category]||0)+x.amount);let rows=Object.entries(m).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;document.querySelector('#screen').innerHTML=`<section class="page"><h2>Laporan</h2><div class="grid" style="margin:15px 0"><div class="card"><span class="muted">Pemasukan</span><div class="money income">${money(i)}</div></div><div class="card"><span class="muted">Pengeluaran</span><div class="money expense">${money(o)}</div></div></div><div class="card"><span class="muted">Selisih</span><div class="money">${money(i-o)}</div><div class="chart">${o?'<div class="donut"></div>':'<div class="empty">Belum ada pengeluaran.</div>'}</div></div><div class="section"><h3>Pengeluaran per kategori</h3></div><div class="card">${rows.map(([n,v])=>`<p style="margin:10px 0"><b>${esc(n)}</b><br>${money(v)} · ${Math.round(v/o*100)}%</p>`).join('')||'<div class="empty">Belum ada data.</div>'}</div><button class="primary" style="margin-top:15px" onclick="exportCSV()">Export CSV</button></section>`}
function settings(){document.querySelector('#screen').innerHTML=`<section class="page"><h2>Pengaturan</h2><div class="card" style="margin-top:15px"><div class="nav"><p>🔐 Security — PIN & biometric (tahap berikutnya)</p><hr><p>🏷️ Kategori — kelola kategori (tahap berikutnya)</p><hr><p>🎨 Tema — tahap berikutnya</p><hr><button class="secondary" onclick="exportJSON()">💾 Backup JSON</button><button class="secondary" onclick="document.querySelector('#restore').click()">♻️ Restore JSON</button><button class="secondary" onclick="exportCSV()">📄 Export CSV</button><input id="restore" type="file" accept=".json" hidden onchange="restore(this.files[0])"></div></div><div class="card" style="margin-top:15px"><b>Hapus semua data</b><p class="muted" style="margin:6px 0 12px">Apaga todas as transações deste dispositivo.</p><button class="secondary danger" onclick="clearAll()">Hapus semua data</button></div><p class="muted" style="text-align:center;margin-top:28px;font-size:12px">© 2026 Sak by ansani</p></section>`}
async function exportJSON(){let data={app:'SAK',version:1,exportedAt:new Date().toISOString(),transactions:await all()};download('Sak_Backup_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data,null,2),'application/json');toast('Backup dibuat')}
async function restore(file){if(!file)return;try{let d=JSON.parse(await file.text());if(!Array.isArray(d.transactions))throw 0;if(!confirm('Restore akan mengganti transaksi saat ini. Lanjutkan?'))return;await new Promise((ok,bad)=>{let r=store(TX,'readwrite').clear();r.onsuccess=ok;r.onerror=bad});for(let x of d.transactions)await put({...x,id:undefined});toast('Data dipulihkan');render()}catch(e){alert('File backup tidak valid.')}}
async function exportCSV(){let tx=await all(),lines=[['No.','Tanggal','Tipe','Kategori','Nominal','Catatan'],...tx.map((x,i)=>[i+1,dt(x.date),x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.amount,x.note||''])];let csv='\ufeff'+lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download('SAK_Transaksi_'+new Date().toISOString().slice(0,10)+'.csv',csv,'text/csv;charset=utf-8');toast('CSV dibuat')}
function download(n,c,t){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:t}));a.download=n;a.click()}
async function clearAll(){if(confirm('Hapus SEMUA data transaksi?')){await new Promise((ok,bad)=>{let r=store(TX,'readwrite').clear();r.onsuccess=ok;r.onerror=bad});toast('Semua data dihapus');go('home')}}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>go(b.dataset.route));
(async()=>{await openDB();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});render()})();
