
const DB='sak-db',VER=3,TX='transactions',CAT='categories',SET='settings';
let db,route='home',filter='all',query='',period='month',editing=null,forcedType='expense',returnRoute='home',state={settings:{},categories:[]},lockTimer;
const DEFAULT_CATS=[
 {id:'income-salary',type:'income',name:'Gaji',icon:'▣',active:true,builtin:true},{id:'income-freelance',type:'income',name:'Freelance',icon:'✦',active:true,builtin:true},{id:'income-gift',type:'income',name:'Hadiah',icon:'♡',active:true,builtin:true},{id:'income-invest',type:'income',name:'Investasi',icon:'↗',active:true,builtin:true},{id:'income-other',type:'income',name:'Lainnya',icon:'＋',active:true,builtin:true},
 {id:'expense-food',type:'expense',name:'Makanan',icon:'●',active:true,builtin:true},{id:'expense-transport',type:'expense',name:'Transportasi',icon:'↗',active:true,builtin:true},{id:'expense-home',type:'expense',name:'Rumah',icon:'⌂',active:true,builtin:true},{id:'expense-shopping',type:'expense',name:'Belanja',icon:'◇',active:true,builtin:true},{id:'expense-bills',type:'expense',name:'Tagihan',icon:'▤',active:true,builtin:true},{id:'expense-health',type:'expense',name:'Kesehatan',icon:'＋',active:true,builtin:true},{id:'expense-edu',type:'expense',name:'Pendidikan',icon:'✦',active:true,builtin:true},{id:'expense-fun',type:'expense',name:'Hiburan',icon:'◉',active:true,builtin:true},{id:'expense-personal',type:'expense',name:'Pribadi',icon:'○',active:true,builtin:true},{id:'expense-other',type:'expense',name:'Lainnya',icon:'＋',active:true,builtin:true}
];
const ICONS=['●','◆','◇','○','△','□','✦','★','♡','♢','⌂','▣','▤','＋','↗','↘','✓','!','?','⚡','☷','◎','◉','✎','☎','▰','◌','◍','⌁','♧','♢','✚'];
function req(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function openDB(){return new Promise((ok,bad)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;let tx=d.objectStoreNames.contains(TX)?null:d.createObjectStore(TX,{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains(CAT))d.createObjectStore(CAT,{keyPath:'id'});if(!d.objectStoreNames.contains(SET))d.createObjectStore(SET,{keyPath:'key'});};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>bad(r.error)})}
function getAll(name){return new Promise((ok,bad)=>{const r=req(name).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function getOne(name,key){return new Promise((ok,bad)=>{const r=req(name).get(key);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function putStore(name,x){return new Promise((ok,bad)=>{const r=req(name,'readwrite').put(x);r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
function delStore(name,key){return new Promise((ok,bad)=>{const r=req(name,'readwrite').delete(key);r.onsuccess=()=>ok();r.onerror=()=>bad(r.error)})}
function clearStore(name){return new Promise((ok,bad)=>{const r=req(name,'readwrite').clear();r.onsuccess=()=>ok();r.onerror=()=>bad(r.error)})}
function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)}
function numMoney(n){return new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(n||0)}
function dt(x){return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(x))}
function isoDate(x){const d=new Date(x);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(s){const t=document.querySelector('#toast');t.className='toast show';t.textContent=s;clearTimeout(t._t);t._t=setTimeout(()=>t.className='toast',1800)}
function go(r){route=r;location.hash=r;render()}
function cat(type){return state.categories.filter(c=>c.type===type&&c.active)}
function catObj(idOrName){return state.categories.find(c=>c.id===idOrName||c.name===idOrName)}
function iconFor(x){return catObj(x.categoryId)?.icon||catObj(x.category)?.icon|| (x.type==='income'?'＋':'−')}
function totals(tx){return {income:tx.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),expense:tx.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0)}}
function range(kind){const now=new Date();let start,end;if(kind==='today'){start=new Date(now.getFullYear(),now.getMonth(),now.getDate());end=new Date(start);end.setDate(end.getDate()+1)}else if(kind==='week'){const day=(now.getDay()+6)%7;start=new Date(now.getFullYear(),now.getMonth(),now.getDate()-day);end=new Date(start);end.setDate(end.getDate()+7)}else if(kind==='year'){start=new Date(now.getFullYear(),0,1);end=new Date(now.getFullYear()+1,0,1)}else if(kind==='prevmonth'){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),1)}else{start=new Date(now.getFullYear(),now.getMonth(),1);end=new Date(now.getFullYear(),now.getMonth()+1,1)}return [start.getTime(),end.getTime()]}
function inRange(x){if(period==='all')return true;const [a,b]=range(period);return x.date>=a&&x.date<b}
function row(x){return `<div class="tx" onclick="detail(${x.id})"><div class="tx-icon">${esc(iconFor(x))}</div><div class="tx-main"><strong>${esc(x.category)}</strong><small>${dt(x.date)}${x.note?' · '+esc(x.note):''}${x.receipt?' · 📷':''}</small></div><div class="tx-amount"><b class="${x.type}">${x.type==='income'?'+':'−'}${money(x.amount)}</b></div></div>`}
function periodBar(){return `<div class="period"><button class="tab ${period==='today'?'active':''}" onclick="period='today';render()">Hari ini</button><button class="tab ${period==='week'?'active':''}" onclick="period='week';render()">Minggu</button><button class="tab ${period==='month'?'active':''}" onclick="period='month';render()">Bulan ini</button><button class="tab ${period==='prevmonth'?'active':''}" onclick="period='prevmonth';render()">Bulan lalu</button><button class="tab ${period==='year'?'active':''}" onclick="period='year';render()">Tahun</button><button class="tab ${period==='all'?'active':''}" onclick="period='all';render()">Semua</button></div>`}
async function render(){document.querySelector('.bottom').style.display='grid';document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.route===route));document.querySelector('#lockBtn').hidden=!state.settings.pinHash;applyTheme();const tx=await getAll(TX);if(route==='home')home(tx);else if(route==='transactions')transactions(tx);else if(route==='add')add();else if(route==='reports')reports(tx);else if(route==='settings')settings();else if(route==='categories')categories();else if(route==='security')security();else if(route==='general')general();else if(route==='data')dataSettings();else if(route==='about')about();else if(route==='detail')detailPage(tx.find(x=>x.id==location.hash.split('/')[1]))}
function home(tx){const t=totals(tx),recent=[...tx].sort((a,b)=>b.date-a.date||b.id-a.id).slice(0,6);document.querySelector('#screen').innerHTML=`<section class="page"><div class="hero"><small>Saldo</small><div class="balance" id="balanceText">${state.settings.hideBalance?'••••••':money(t.income-t.expense)}</div></div><div class="grid"><div class="card summary-card"><span class="muted">Pemasukan</span><div class="money income">${state.settings.hideBalance?'••••':money(t.income)}</div></div><div class="card summary-card"><span class="muted">Pengeluaran</span><div class="money expense">${state.settings.hideBalance?'••••':money(t.expense)}</div></div></div><div class="actions"><button class="action income" onclick="newTx('income','home')">＋ Pemasukan</button><button class="action expense" onclick="newTx('expense','home')">− Pengeluaran</button></div><div class="section"><h3>Transaksi terbaru</h3><button class="link" onclick="go('transactions')">Lihat semua</button></div><div class="card">${recent.map(row).join('')||`<div class="empty"><strong>Belum ada transaksi</strong>Yuk mulai mencatat keuanganmu.</div>`}</div></section>`}
function transactions(tx){let l=tx.filter(x=>filter==='all'||x.type===filter).filter(x=>(x.category+' '+(x.note||'')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date-a.date||b.id-a.id);document.querySelector('#screen').innerHTML=`<section class="page"><h2>Transaksi</h2><input class="search" placeholder="Cari transaksi..." value="${esc(query)}" oninput="query=this.value;render()"><div class="toolbar"><button class="tab ${filter==='all'?'active':''}" onclick="filter='all';render()">Semua</button><button class="tab ${filter==='income'?'active':''}" onclick="filter='income';render()">Pemasukan</button><button class="tab ${filter==='expense'?'active':''}" onclick="filter='expense';render()">Pengeluaran</button></div><div class="card">${l.map(row).join('')||'<div class="empty">Tidak ada transaksi.</div>'}</div><button class="primary" style="margin-top:15px" onclick="newTx('expense','transactions')">＋ Tambah transaksi</button></section>`}
function newTx(t='expense',back='home'){editing=null;forcedType=t;returnRoute=back;go('add')}
function add(){const x=editing,type=x?.type||forcedType;const cs=cat(type);document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>${x?'Edit':'Tambah'} Transaksi</h2><button class="link" onclick="go('${returnRoute}')">Batal</button></div><form class="form" onsubmit="save(event)"><div class="field"><label>Tipe</label><select id="type" onchange="refreshCatOptions()"><option value="income" ${type==='income'?'selected':''}>Pemasukan</option><option value="expense" ${type==='expense'?'selected':''}>Pengeluaran</option></select></div><div class="field"><label>Nominal</label><input id="amount" class="amount" inputmode="numeric" type="number" min="1" step="1" required value="${x?.amount||''}" placeholder="Rp 0"></div><div class="field"><label>Kategori</label><select id="category">${cs.map(c=>`<option value="${esc(c.id)}" ${(x?.categoryId===c.id||(!x?.categoryId&&x?.category===c.name))?'selected':''}>${esc(c.icon)} ${esc(c.name)}</option>`).join('')}</select><button type="button" class="link" style="text-align:left;padding:0" onclick="go('categories')">＋ Kelola kategori</button></div><div class="field"><label>Tanggal</label><input id="date" type="date" required value="${x?isoDate(x.date):isoDate(Date.now())}"></div><div class="field"><label>Catatan (opsional)</label><textarea id="note" rows="3" placeholder="Misalnya: makan siang, belanja bulanan...">${esc(x?.note||'')}</textarea></div><div class="field"><label>Bukti/struk (opsional)</label><input id="receipt" type="file" accept="image/*" capture="environment"><small class="muted">Bisa ambil kamera atau pilih dari galeri.</small>${x?.receipt?`<img class="receipt-preview" src="${x.receipt}" alt="Struk"><label><input id="removeReceipt" type="checkbox"> Hapus struk lama</label>`:''}</div><div class="form-actions"><button type="button" class="secondary" onclick="go('${returnRoute}')">Batal</button><button class="primary">${x?'Simpan perubahan':'Simpan transaksi'}</button></div></form></section>`}
function refreshCatOptions(){const type=document.querySelector('#type').value;const el=document.querySelector('#category');el.innerHTML=cat(type).map(c=>`<option value="${esc(c.id)}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}
async function save(e){e.preventDefault();const type=document.querySelector('#type').value,categoryId=document.querySelector('#category').value,c=catObj(categoryId);const amount=Number(document.querySelector('#amount').value);if(!(amount>0)||!c){toast('Nominal dan kategori wajib diisi');return}const file=document.querySelector('#receipt')?.files?.[0];let receipt=editing?.receipt||null;if(file){if(file.size>4*1024*1024){toast('Foto maksimal 4 MB');return}receipt=await resizeImage(file)}if(document.querySelector('#removeReceipt')?.checked)receipt=null;const x={id:editing?.id,type,amount,categoryId,category:c.name,date:new Date(document.querySelector('#date').value+'T12:00:00').getTime(),note:document.querySelector('#note').value.trim(),receipt,createdAt:editing?.createdAt||Date.now(),updatedAt:Date.now()};await putStore(TX,x);toast(editing?'Transaksi diperbarui':'Transaksi tersimpan');editing=null;go(returnRoute)}
function resizeImage(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78))};im.onerror=reject;im.src=fr.result};fr.onerror=reject;fr.readAsDataURL(file)})}
async function detail(id){location.hash='detail/'+id;route='detail';render()}
async function detailPage(x){if(!x){go('transactions');return}document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Detail Transaksi</h2><button class="link" onclick="go('transactions')">Kembali</button></div><div class="card"><span class="muted">${x.type==='income'?'Pemasukan':'Pengeluaran'}</span><h1 class="${x.type}" style="font-size:34px;margin:6px 0 20px">${x.type==='income'?'+':'−'}${money(x.amount)}</h1><p><b>Kategori</b><br>${esc(x.category)}</p><p style="margin-top:15px"><b>Tanggal</b><br>${dt(x.date)}</p><p style="margin-top:15px"><b>Catatan</b><br>${esc(x.note||'—')}</p>${x.receipt?`<div style="margin-top:15px"><b>Struk</b><img class="receipt-preview" src="${x.receipt}" alt="Struk"></div>`:''}</div><div class="actions"><button class="action" onclick="edit(${x.id})">✎ Edit</button><button class="action danger" onclick="removeTx(${x.id})">Hapus</button></div></section>`}
async function edit(id){editing=(await getAll(TX)).find(x=>x.id===id);returnRoute='transactions';go('add')}
async function removeTx(id){if(confirm('Hapus transaksi ini secara permanen?')){await delStore(TX,id);toast('Transaksi dihapus');go('transactions')}}
function reports(tx){const list=tx.filter(inRange),t=totals(list),rows=Object.entries(list.filter(x=>x.type==='expense').reduce((m,x)=>(m[x.category]=(m[x.category]||0)+x.amount,m),{})).sort((a,b)=>b[1]-a[1]),max=rows[0]?.[1]||1;const months=monthBuckets(list);document.querySelector('#screen').innerHTML=`<section class="page"><h2>Laporan</h2>${periodBar()}<div class="grid"><div class="card summary-card"><span class="muted">Pemasukan</span><div class="money income">${money(t.income)}</div></div><div class="card summary-card"><span class="muted">Pengeluaran</span><div class="money expense">${money(t.expense)}</div></div></div><div class="card" style="margin-top:12px"><span class="muted">Selisih</span><div class="money ${t.income-t.expense<0?'negative':''}" style="font-size:25px">${money(t.income-t.expense)}</div></div><div class="card" style="margin-top:12px"><div class="section" style="margin-top:0"><h3>Pengeluaran per kategori</h3><span class="badge">${rows.length} kategori</span></div>${rows.length?`<div class="donut" style="background:${donutGradient(rows)}"></div><div class="legend">${rows.slice(0,6).map(([n,v],i)=>`<div class="legend-row"><span class="dot" style="background:${chartColor(i)}"></span><span style="flex:1">${esc(n)}</span><b>${money(v)}</b></div>`).join('')}</div>`:'<div class="empty">Belum ada pengeluaran pada periode ini.</div>'}</div><div class="card" style="margin-top:12px"><div class="section" style="margin-top:0"><h3>Tren pemasukan vs pengeluaran</h3></div>${trendHtml(months)}</div><div class="card" style="margin-top:12px"><h3>Kategori pengeluaran terbesar</h3>${rows[0]?`<div style="font-size:24px;font-weight:800;margin-top:6px">${esc(rows[0][0])}</div><div class="muted">${money(rows[0][1])}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,rows[0][1]/max*100)}%"></div></div>`:'<div class="empty">Belum ada data.</div>'}</div><div class="actions no-print"><button class="action" onclick="exportCSV()">CSV</button><button class="action" onclick="exportXLSX()">Excel</button></div><button class="primary no-print" onclick="printPDF()">PDF / Cetak laporan</button></section>`}
function chartColor(i){return ['#3157d5','#7957d5','#58a98a','#e5a34a','#e05252','#6e7ca1'][i%6]}
function donutGradient(rows){const total=rows.reduce((a,x)=>a+x[1],0);let cur=0;return `conic-gradient(${rows.slice(0,6).map(([n,v],i)=>{const a=cur/total*100;cur+=v;const b=cur/total*100;return `${chartColor(i)} ${a}% ${b}%`}).join(',')})`}
function monthBuckets(tx){const out=[];const now=new Date();for(let i=5;i>=0;i--){const d=new Date(now.getFullYear(),now.getMonth()-i,1),e=new Date(now.getFullYear(),now.getMonth()-i+1,1);const a=tx.filter(x=>x.date>=d&&x.date<e),t=totals(a);out.push({label:new Intl.DateTimeFormat('id-ID',{month:'short'}).format(d),income:t.income,expense:t.expense})}return out}
function trendHtml(ms){const mx=Math.max(1,...ms.map(x=>Math.max(x.income,x.expense)));return `<div class="trend">${ms.map(x=>`<div class="trend-col"><div class="trend-bars"><div class="trend-bar in" style="height:${Math.max(2,x.income/mx*100)}%"></div><div class="trend-bar out" style="height:${Math.max(2,x.expense/mx*100)}%"></div></div><div class="trend-label">${esc(x.label)}</div></div>`).join('')}</div><div class="small muted" style="margin-top:8px">● Pemasukan &nbsp; ● Pengeluaran</div>`}
function settings(){document.querySelector('#screen').innerHTML=`<section class="page"><h2>Pengaturan</h2><div class="card"><div class="settings-list"><button class="setting-item" onclick="go('security')"><span class="setting-left"><span class="setting-icon">🔐</span><span><b>Security</b><br><small class="muted">PIN, biometrik & kunci otomatis</small></span></span><span>›</span></button><button class="setting-item" onclick="go('data')"><span class="setting-left"><span class="setting-icon">💾</span><span><b>Data</b><br><small class="muted">Backup, restore & export</small></span></span><span>›</span></button><button class="setting-item" onclick="go('categories')"><span class="setting-left"><span class="setting-icon">🏷️</span><span><b>Kategori</b><br><small class="muted">Tambah, edit & nonaktifkan</small></span></span><span>›</span></button><button class="setting-item" onclick="go('general')"><span class="setting-left"><span class="setting-icon">🎨</span><span><b>Umum</b><br><small class="muted">Tema, format tanggal & preferensi</small></span></span><span>›</span></button><button class="setting-item" onclick="go('about')"><span class="setting-left"><span class="setting-icon">ⓘ</span><span><b>Tentang</b><br><small class="muted">Info aplikasi & versi</small></span></span><span>›</span></button></div></div><div class="footer">© 2026 Sak by ansani</div></section>`}
function security(){document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Security</h2><button class="link" onclick="go('settings')">Kembali</button></div><div class="card"><div class="setting-item"><span><b>PIN aplikasi</b><br><small class="muted">${state.settings.pinHash?'PIN aktif':'PIN belum diatur'}</small></span><button class="secondary" onclick="setPin()">${state.settings.pinHash?'Ubah':'Atur PIN'}</button></div><div class="setting-item"><span><b>Biometrik</b><br><small class="muted">Gunakan sidik jari/biometrik jika tersedia</small></span><label class="switch"><input type="checkbox" ${state.settings.biometric?'checked':''} onchange="toggleBiometric(this.checked)"><span class="slider"></span></label></div><div class="setting-item"><span><b>Kunci otomatis</b><br><small class="muted">Kunci setelah tidak aktif</small></span><select style="width:auto" onchange="saveSetting('autoLock',this.value)"><option value="0" ${String(state.settings.autoLock||0)==='0'?'selected':''}>Tidak</option><option value="5" ${String(state.settings.autoLock)==='5'?'selected':''}>5 menit</option><option value="15" ${String(state.settings.autoLock)==='15'?'selected':''}>15 menit</option><option value="30" ${String(state.settings.autoLock)==='30'?'selected':''}>30 menit</option></select></div><div class="setting-item"><span><b>Sembunyikan saldo</b><br><small class="muted">Sembunyikan nominal di Beranda</small></span><label class="switch"><input type="checkbox" ${state.settings.hideBalance?'checked':''} onchange="saveSetting('hideBalance',this.checked)"><span class="slider"></span></label></div></div></section>`}
async function setPin(){const p=prompt(state.settings.pinHash?'Masukkan PIN baru (4–6 angka)':'Buat PIN aplikasi (4–6 angka)');if(p===null)return;if(!/^\d{4,6}$/.test(p)){alert('PIN harus 4–6 angka.');return}state.settings.pinHash=await hash(p);await saveSetting('pinHash',state.settings.pinHash);toast('PIN disimpan');render()}
async function unlock(){const p=document.querySelector('#unlockPin').value;if(await hash(p)!==state.settings.pinHash){document.querySelector('#unlockMsg').textContent='PIN salah.';return}document.querySelector('#screen').innerHTML='';startLockTimer();render()}
async function hash(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function toggleBiometric(v){if(!v){state.settings.biometric=false;await saveSetting('biometric',false);toast('Biometrik dimatikan');return}if(!window.PublicKeyCredential){toast('Biometrik tidak tersedia di browser ini');render();return}try{const challenge=crypto.getRandomValues(new Uint8Array(32));const cred=await navigator.credentials.create({publicKey:{challenge,rp:{name:'SAK',id:location.hostname},user:{id:crypto.getRandomValues(new Uint8Array(16)),name:'sak-local',displayName:'SAK'},pubKeyCredParams:[{type:'public-key',alg:-7}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required'}}});state.settings.biometric=!!cred;state.settings.bioId=cred?btoa(String.fromCharCode(...new Uint8Array(cred.rawId))):null;await saveSetting('biometric',state.settings.biometric);await saveSetting('bioId',state.settings.bioId);toast('Biometrik diaktifkan')}catch(e){toast('Biometrik belum bisa diaktifkan di perangkat ini');render()}}
function general(){document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Umum</h2><button class="link" onclick="go('settings')">Kembali</button></div><div class="card"><div class="setting-item"><span><b>Tema</b><br><small class="muted">Pilih tampilan SAK</small></span><select style="width:auto" onchange="saveSetting('theme',this.value)"><option value="system" ${state.settings.theme==='system'?'selected':''}>Sistem</option><option value="light" ${state.settings.theme==='light'?'selected':''}>Terang</option><option value="dark" ${state.settings.theme==='dark'?'selected':''}>Gelap</option></select></div><div class="setting-item"><span><b>Mata uang</b><br><small class="muted">Mata uang utama</small></span><span class="badge">IDR</span></div><div class="setting-item"><span><b>Format tanggal</b><br><small class="muted">Contoh tampilan tanggal</small></span><span class="badge">DD MMM YYYY</span></div><div class="setting-item"><span><b>Konfirmasi sebelum hapus</b><br><small class="muted">Minta konfirmasi saat menghapus transaksi</small></span><label class="switch"><input type="checkbox" ${state.settings.confirmDelete!==false?'checked':''} onchange="saveSetting('confirmDelete',this.checked)"><span class="slider"></span></label></div><div class="setting-item"><span><b>Minggu dimulai</b><br><small class="muted">Digunakan untuk filter Minggu</small></span><span class="badge">Senin</span></div></div></section>`}
function dataSettings(){document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Data</h2><button class="link" onclick="go('settings')">Kembali</button></div><div class="notice">Backup menyimpan data SAK dalam JSON agar bisa dipulihkan di perangkat lain. Export digunakan untuk dibaca/diproses di luar aplikasi.</div><div class="card"><button class="primary" onclick="exportJSON()">💾 Backup JSON</button><div class="actions"><button class="action" onclick="document.querySelector('#restore').click()">♻️ Restore JSON</button><button class="action" onclick="exportCSV()">📄 CSV</button></div><div class="actions"><button class="action" onclick="exportXLSX()">📊 Excel</button><button class="action" onclick="printPDF()">📑 PDF</button></div><input id="restore" type="file" accept="application/json,.json" hidden onchange="restore(this.files[0])"></div><div class="card danger-box" style="margin-top:12px"><b>Hapus semua data</b><p class="muted small" style="margin:6px 0 12px">Menghapus seluruh transaksi dan receipt dari perangkat ini.</p><button class="secondary danger" onclick="clearAll()">Hapus semua data</button></div></section>`}
function categories(){const type=state.settings.catType||'expense',list=state.categories.filter(c=>c.type===type);document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Kategori</h2><button class="link" onclick="go('settings')">Kembali</button></div><div class="toolbar"><button class="tab ${type==='income'?'active':''}" onclick="state.settings.catType='income';render()">Pemasukan</button><button class="tab ${type==='expense'?'active':''}" onclick="state.settings.catType='expense';render()">Pengeluaran</button></div><div class="card"><div class="section" style="margin-top:0"><h3>${type==='income'?'Kategori pemasukan':'Kategori pengeluaran'}</h3><button class="primary" style="width:auto;padding:9px 12px" onclick="categoryModal('${type}')">＋ Tambah</button></div><div class="category-list">${list.map(c=>`<div class="cat-row"><span class="tx-icon">${esc(c.icon)}</span><span class="cat-name">${esc(c.name)} ${!c.active?'<span class="badge">Nonaktif</span>':''}</span><div class="cat-actions"><button class="mini" onclick="categoryModal('${c.type}','${c.id}')">✎</button><button class="mini" onclick="toggleCategory('${c.id}')">${c.active?'◌':'✓'}</button></div></div>`).join('')}</div></div><div class="notice" style="margin-top:12px">Kategori yang pernah dipakai transaksi sebaiknya dinonaktifkan, bukan dihapus, agar riwayat tetap aman.</div></section>`}
function categoryModal(type,id=''){const c=id?state.categories.find(x=>x.id===id):null,sel=c?.icon||ICONS[0];document.querySelector('#modal').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h3>${c?'Edit':'Tambah'} kategori</h3><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveCategory(event,'${type}','${id}')"><div class="field"><label>Nama kategori</label><input id="catName" required maxlength="30" value="${esc(c?.name||'')}"></div><div class="field"><label>Ikon</label><div class="icon-grid">${ICONS.map(i=>`<button type="button" class="icon-choice ${i===sel?'active':''}" data-icon="${esc(i)}" onclick="chooseIcon(this)">${esc(i)}</button>`).join('')}</div><input id="catIcon" type="hidden" value="${esc(sel)}"></div><button class="primary">Simpan kategori</button></form></div></div>`}
function chooseIcon(b){document.querySelectorAll('.icon-choice').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#catIcon').value=b.dataset.icon}
function closeModal(){document.querySelector('#modal').innerHTML=''}
async function saveCategory(e,type,id){e.preventDefault();const name=document.querySelector('#catName').value.trim(),icon=document.querySelector('#catIcon').value;if(!name)return;let c=id?state.categories.find(x=>x.id===id):null;if(c){c.name=name;c.icon=icon}else{c={id:crypto.randomUUID(),type,name,icon,active:true,builtin:false};state.categories.push(c)}await putStore(CAT,c);closeModal();toast('Kategori disimpan');render()}
async function toggleCategory(id){const c=state.categories.find(x=>x.id===id);if(!c)return;c.active=!c.active;await putStore(CAT,c);toast(c.active?'Kategori diaktifkan':'Kategori dinonaktifkan');render()}
function about(){document.querySelector('#screen').innerHTML=`<section class="page"><div class="section"><h2>Tentang</h2><button class="link" onclick="go('settings')">Kembali</button></div><div class="card" style="text-align:center"><img src="icons/icon.svg" class="lock-logo"><h2 style="margin:8px 0 2px">SAK</h2><p class="muted">Catatan Keuangan Pribadi</p><p class="badge" style="display:inline-block;margin-top:12px">Versi 1.1</p><p class="footer">© 2026 Sak by ansani</p></div></section>`}
async function saveSetting(key,value){state.settings[key]=value;await putStore(SET,{key,value});applyTheme();toast('Pengaturan disimpan');if(route!=='security'&&route!=='general')render()}
function applyTheme(){const t=state.settings.theme||'system',dark=t==='dark'||(t==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark)}
async function loadState(){state.categories=await getAll(CAT);if(!state.categories.length){for(const c of DEFAULT_CATS)await putStore(CAT,c);state.categories=[...DEFAULT_CATS]}const ss=await getAll(SET);state.settings=Object.fromEntries(ss.map(x=>[x.key,x.value]));state.settings.theme??='system';state.settings.confirmDelete??=true;state.settings.autoLock??=0}
function lockScreen(){document.querySelector('#screen').innerHTML=`<section class="locked"><div class="card lock-card"><img src="icons/icon.svg" class="lock-logo"><h2>SAK terkunci</h2><p class="muted" style="margin-bottom:16px">Masukkan PIN untuk melanjutkan.</p><input id="unlockPin" inputmode="numeric" type="password" maxlength="6" placeholder="PIN"><button class="primary" style="margin-top:10px" onclick="unlock()">Buka SAK</button><p id="unlockMsg" class="expense small" style="margin-top:10px"></p></div></section>`;document.querySelector('.bottom').style.display='none'}
function startLockTimer(){clearTimeout(lockTimer);const min=Number(state.settings.autoLock||0);if(!state.settings.pinHash||!min)return;lockTimer=setTimeout(()=>{lockScreen()},min*60000)}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function exportJSON(){const data={app:'SAK',version:'1.1',exportedAt:new Date().toISOString(),settings:state.settings,categories:state.categories,transactions:await getAll(TX)};download('Sak_Backup_'+isoDate(Date.now())+'.json',JSON.stringify(data,null,2),'application/json');toast('Backup JSON dibuat')}
async function restore(file){if(!file)return;try{const d=JSON.parse(await file.text());if(!Array.isArray(d.transactions))throw Error();if(!confirm('Restore akan mengganti transaksi, kategori, dan pengaturan saat ini. Lanjutkan?'))return;await clearStore(TX);for(const x of d.transactions)await putStore(TX,{...x});if(Array.isArray(d.categories)){await clearStore(CAT);for(const c of d.categories)await putStore(CAT,c)}if(d.settings){await clearStore(SET);for(const [key,value] of Object.entries(d.settings))await putStore(SET,{key,value})}await loadState();toast('Data berhasil dipulihkan');render()}catch(e){alert('File backup tidak valid atau rusak.')}}
async function exportCSV(){const tx=await getAll(TX),lines=[['No.','Tanggal','Tipe','Kategori','Nominal','Catatan'],...tx.sort((a,b)=>a.date-b.date).map((x,i)=>[i+1,dt(x.date),x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.amount,x.note||''])];const csv='\ufeff'+lines.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download('SAK_Transaksi_'+isoDate(Date.now())+'.csv',csv,'text/csv;charset=utf-8');toast('CSV dibuat')}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function u16(n){return [n&255,(n>>>8)&255]}function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function zipStore(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;for(const f of files){const data=typeof f.data==='string'?enc.encode(f.data):f.data,name=enc.encode(f.name),crc=crc32(data);const head=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name,...data]);parts.push(head);const cen=new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]);central.push(cen);offset+=head.length}const cd=central.reduce((a,b)=>a+b.length,0),end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(cd),...u32(offset),...u16(0)]);return new Blob([...parts,...central,end],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})}
function xml(s){return esc(s).replace(/&amp;quot;/g,'&quot;')}
async function exportXLSX(){const tx=await getAll(TX),rows=[['No.','Tanggal','Tipe','Kategori','Nominal','Catatan'],...tx.sort((a,b)=>a.date-b.date).map((x,i)=>[i+1,dt(x.date),x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.amount,x.note||''])];const cells=(r,rowNum)=>r.map((v,i)=>`<c r="${String.fromCharCode(65+i)}${rowNum}" t="${typeof v==='number'?'n':'inlineStr'}">${typeof v==='number'?`<v>${v}</v>`:`<is><t>${xml(String(v))}</t></is>`}</c>`).join('');const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((r,i)=>`<row>${cells(r,i+1)}</row>`).join('')}</sheetData></worksheet>`;const wb=`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Semua Transaksi" sheetId="1" r:id="rId1"/></sheets></workbook>`;const rel=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`;const root=`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;const ct=`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`;download('SAK_Transaksi_'+isoDate(Date.now())+'.xlsx',zipStore([{name:'[Content_Types].xml',data:ct},{name:'_rels/.rels',data:root},{name:'xl/workbook.xml',data:wb},{name:'xl/_rels/workbook.xml.rels',data:rel},{name:'xl/worksheets/sheet1.xml',data:sheet}]),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');toast('Excel dibuat')}
function pdfEsc(s){return String(s??'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
function makePDF(pages){const objs=[];const add=x=>{objs.push(x);return objs.length};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');const pageIds=[];const contentIds=[];for(const cmds of pages){const content=cmds.join('\n');contentIds.push(add(`<< /Length ${content.length} >>\nstream\n${content}\nendstream`));pageIds.push(add(''));}const pagesId=add('');for(let i=0;i<pageIds.length;i++)objs[pageIds[i]-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`;objs[pagesId-1]=`<< /Type /Pages /Kids [${pageIds.map(x=>x+' 0 R').join(' ')}] /Count ${pageIds.length} >>`;const catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);let pdf='%PDF-1.4\n',offs=[0];for(let i=0;i<objs.length;i++){offs[i+1]=pdf.length;pdf+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objs.length;i++)pdf+=String(offs[i]).padStart(10,'0')+' 00000 n \n';pdf+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:'application/pdf'})}
function printPDF(){const print=window.open('','_blank');if(!print){alert('Izinkan pop-up untuk membuat laporan PDF.');return}getAll(TX).then(tx=>{const list=tx.filter(inRange),t=totals(list),rows=Object.entries(list.filter(x=>x.type==='expense').reduce((m,x)=>(m[x.category]=(m[x.category]||0)+x.amount,m),{})).sort((a,b)=>b[1]-a[1]);const page=[];let y=790;const c=[];const text=(s,x,y,size=11,bold=false)=>c.push(`BT /F1 ${size} Tf ${x} ${y} Td (${pdfEsc(s)}) Tj ET`);text('LAPORAN KEUANGAN',40,y,20,true);y-=24;text('SAK - Catatan Keuangan Pribadi',40,y,11);y-=18;text('Pemasukan: '+money(t.income),40,y,11);text('Pengeluaran: '+money(t.expense),230,y,11);text('Selisih: '+money(t.income-t.expense),410,y,11);y-=30;text('PENGELUARAN PER KATEGORI',40,y,13,true);y-=20;const mx=rows[0]?.[1]||1;for(const [n,v] of rows.slice(0,8)){text(n,40,y,10);text(money(v),430,y,10);c.push(`${40} ${y-6} m 400 ${y-6} l S`);c.push(`40 ${y-4} 360 7 re f`);c.push(`40 ${y-4} ${360*v/mx} 7 re f`);y-=20}y-=10;text('TRANSAKSI',40,y,13,true);y-=18;const headers=['No.','Tanggal','Tipe','Kategori','Nominal','Catatan'];text(headers.join('   '),40,y,8,true);y-=15;for(let i=0;i<list.length;i++){if(y<45){page.push(c.splice(0,c.length));y=790;text('LAPORAN KEUANGAN - LANJUTAN',40,y,16,true);y-=25;text(headers.join('   '),40,y,8,true);y-=15}const x=list.sort((a,b)=>a.date-b.date)[i];const line=`${i+1}   ${dt(x.date)}   ${x.type==='income'?'Pemasukan':'Pengeluaran'}   ${x.category}   ${money(x.amount)}   ${(x.note||'').slice(0,35)}`;text(line,40,y,7);y-=13}text('Dibuat dengan SAK app by ansani',40,25,7);page.push(c);const cmds=page.length?page:[c];const pdf=makePDF(cmds);const url=URL.createObjectURL(pdf);print.document.write(`<html><head><title>SAK - Laporan</title></head><body style="margin:0"><embed src="${url}" type="application/pdf" width="100%" height="100%" style="position:fixed;inset:0"></body></html>`);print.document.close();toast('PDF laporan dibuat')})}
async function clearAll(){if(!confirm('Hapus SEMUA transaksi, kategori custom, pengaturan, dan receipt?'))return;await clearStore(TX);await clearStore(CAT);await clearStore(SET);await loadState();toast('Semua data dihapus');go('home')}
function touch(){startLockTimer()}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>go(b.dataset.route));document.querySelector('#lockBtn').onclick=()=>lockScreen();['click','touchstart','keydown'].forEach(e=>window.addEventListener(e,touch,{passive:true}));window.matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',applyTheme);
(async()=>{await openDB();await loadState();applyTheme();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});if(state.settings.pinHash){lockScreen()}else{render()}startLockTimer()})();
